language: ruby
sudo: false
cache: bundler
rvm:
   - 2.4
script: bundle exec jekyll build && htmlproofer --check-html --disable-external ./_site
install: bundle install

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
