name: Sangyyes Blog Archiv
pygments: true

#site configuration
permalink: /:year/:month/:title/
plugins: _plugins
#baseurl: /
#Author
author: Christian Vervoorts
short: I do things
email: info@sangyye.de

#social things
github: sangyye
twitter: sangyye
