name: Sangyyes Blog Archiv

#site configuration
permalink: /:year/:month/:title/
#set url for api.json
production_url: http://blog.sangyye.de
baseurl: /
#Author
author: Christian Vervoorts
short: I do things
email: info@sangyye.de

#social things
github: sangyye
twitter: sangyye
